defaults:
  env:
    src: production
    src: development 
  dump: mysqldump

projects:
  - 'project'

project:
  development:
    username: root
    password:  
    host: localhost
  production:
    username: ruby
    password:  
    host: localhost
