defaults:
  env: production

projects:
  - 'ndseg'

project:
  development:
    username: root
    password:  
    host: localhost
  production:
    username: ruby
    password:  
    host: localhost
