defaults:
  env:
    src: production
    tgt: development
  dump: mysqldump
  cmd: mysql
  admin: mysqladmin
  purge: false


environments:
  development:
    username: root
    passowrd:
    host: localhost
  production:
    username: ruby
    password:
    host: mysql.example.com


projects:
  - 'my_project'


my_project:
  development:
    database: my_project_development
    dependencies:
      - 'dep_db_1_development'
      - 'dep_db_2_development'
  development:
    database: my_project_production
    dependencies:
      - 'dep_db_1_production'
      - 'dep_db_2_production'
